version: "3.7"

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true

services:
# This one will need to work witout Cloudflare, 
# because Theo handles DNS for HuPI.org
  hupi:
    container_name: hupi
    image: caddy:latest
    environment:
      TZ: 'America/Los_Angeles'
    labels:
      caddy: ${HUPI_FQDN} #### needed for caddy to redirect traffic
      #caddy.servers.protocols: "experimental_http3" #### For HTTP/3
      #caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" ### Only if you will prefer ZeroSSL. Default it is Let's Encypt.
      #caddy.tls.ca: "https://acme-staging-v02.api.letsencrypt.org/directory" # Needed only for testing purpose. Remove this line after you finished your tests.
      caddy.reverse_proxy: "{{upstreams 8088}}" #### needed to tell caddy which port number should send traffic
      caddy.tls.protocols: "tls1.3" #### This is optional. Default it is tls1.2
#      caddy.tls.dns: "cloudflare ${CLOUDFLARE_API_TOKEN}"
    volumes:
      - ./Caddyfile.hupi:/etc/caddy/Caddyfile
      - ./content:/srv #### content to be served
    networks:
      - proxy
    restart: unless-stopped
    