version: "3.7"

networks:
  proxy:
    name: ${NETWORK_NAME}
    external: true

services:
  hupi:
    container_name: hupi
    image: caddy:latest
    environment:
      TZ: 'America/Los_Angeles'
    labels:
      caddy: ${HUPI_FQDN} #### needed for caddy to redirect traffic
      #caddy.servers.protocols: "experimental_http3" #### For HTTP/3
      #caddy.tls.ca: "https://acme.zerossl.com/v2/DV90" ### Only if you will prefer ZeroSSL. Default it is Let's Encypt.
      #caddy.tls.ca: "https://acme-staging-v02.api.letsencrypt.org/directory" # Needed only for testing purpose. Remove this line after you finished your tests.
      caddy.reverse_proxy: "{{upstreams}}" 
      caddy.tls.protocols: "tls1.3" #### This is optional. Default it is tls1.2
      caddy.tls.dns: "cloudflare ${CLOUDFLARE_API_TOKEN}"
    volumes:
      - ./Caddyfile.hupi:/etc/caddy/Caddyfile:ro
      - ./content:/srv:ro #### content to be served
    networks:
      - proxy
    restart: unless-stopped
    
  phpfpm:
    # Note this same image is used for wiki.wildsong.biz
    container_name: hupi-php
    image: phpfpm:latest
    volumes:
      - ./content:/srv:ro
    networks:
      proxy:
        aliases:
          - hupiphp
    restart: unless-stopped
        
